#' plot a slopeflex object
#' @param sx_obj an object generated by `slopeflex_run_model`
#' @export

plot.slopeflex <- function(sx_obj, ...) {

  stopifnot(class(sx_obj) %in% 'slopeflex')
  engine = sx_obj$engine
  y = sx_obj$y
  yhat = sx_obj$yhat
  yhat_fc = sx_obj$yhat_fc
  yhat_LB = sx_obj$yhat_LB
  yhat_UB = sx_obj$yhat_UB
  x = sx_obj$x
  x_fc = sx_obj$x_fc

  # output plots -----------
  plot(yhat_fc, x = x_fc, ylim = c(min(yhat_LB), max(yhat_UB)),
       xlim = c(min(x_fc), max(x_fc)),
       type = 'l', lty = 3, lwd = 2,
       col = 4, sub = sprintf("engine = '%s'", engine), cex.sub = .7,
       ...)
  polygon(x = c(x_fc,rev(x_fc)),
          y = c(yhat_LB, rev(yhat_UB)),
          border = NA, col = scales::alpha('gray50', .3))
  lines(yhat, x = x, lty = 1, lwd = 2, col = 1)
  points(y, x = x, pch = 20, col = 2)

}