#' plot a slopeflex object
#' @param fit an rstan object generated by `slopeflex_run_model` with `rstan` engine.

slopeflex_plot_fit <- function(fit) {

  stopifnot(attr(fit, 'slopeflex'))
  ds = attr(fit, 'ds')

  yhat_CI <- function(fit, par = 'yhat_fc', p) {
    XB <- rstan::extract(fit)[[par]]
    sig <- rstan::extract(fit)[['sig']]
    sims <- c(XB) + rnorm(length(XB), 0, c(sig))
    apply(matrix(sims, nrow(XB), ncol(XB)), 2, quantile, p)
  }
  n_chains = length(fit@stan_args)
  col_name = if(n_chains == 1) 'mean-chain:1' else 'mean-all chains'
  yhat <- rstan::get_posterior_mean(fit, pars = 'yhat')[,col_name]
  yhat_fc <- rstan::get_posterior_mean(fit, pars = 'yhat_fc')[,col_name]
  xx <- rstan::get_posterior_mean(fit, pars = 'x_fc')[,col_name]
  x <- rstan::get_posterior_mean(fit, pars = 'x')[,col_name]
  x <- x + min(dates)
  xx <- xx + min(dates)
  yhat_LB = yhat_CI(fit, p = .05)
  yhat_UB = yhat_CI(fit, p = .95)

  # output plots -----------
  plot(yhat_fc, x = xx, ylim = c(min(yhat_LB), max(yhat_UB)),
       xlim = c(min(xx), max(xx)), ylab = 'yhat', xlab = 'date',
       type = 'l', lty = 3, lwd = 2,
       col = 4)
  polygon(x = c(xx,rev(xx)),
          y = c(yhat_LB, rev(yhat_UB)),
          border = NA, col = scales::alpha('gray50', .3))
  lines(yhat, x = x, lty = 1, lwd = 2, col = 1)
  points(ds$y, x = x, pch = 20, col = 2)

}